/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package se1621.service;

import jakarta.servlet.ServletContext;
import se1621.dto.User;
import se1621.utils.EmailUtils;
import se1621.utils.JwtTokenUtils;

/**
 *
 * @author ACER
 */
public class EmailServiceIml implements EmailService {

    private static final String EMAIL_WELCOME_SUBJECT = "Welcome to FuJob";
    private static final String EMAIL_FORGOT_PASSWORD = "Reset your FuJob password";

    @Override
    public void sendEmail(ServletContext context, User repliient, String type) {
        String host = context.getInitParameter("host");
        String port = context.getInitParameter("port");
        String user = context.getInitParameter("user");
        String pass = context.getInitParameter("pass");
        try {
            String content = null;
            String subject = null;
            switch (type) {
                case "welcome":
                    subject = EMAIL_WELCOME_SUBJECT;
                    content = "<!DOCTYPE html>\n"
                            + "<html lang=\"en\" class=\"no-js\">\n"
                            + "\n"
                            + "<head>\n"
                            + "    <meta charset=\"UTF-8\">\n"
                            + "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\n"
                            + "    <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />\n"
                            + "    <style type=\"text/css\">\n"
                            + "        .body {\n"
                            + "            width: 100% !important;\n"
                            + "            height: 100%;\n"
                            + "            margin: 0;\n"
                            + "            line-height: 1.4;\n"
                            + "            background-color: #f2f4f6;\n"
                            + "            color: #74787e;\n"
                            + "            -webkit-text-size-adjust: none\n"
                            + "        }\n"
                            + "\n"
                            + "        @media only screen and (max-width: 600px) {\n"
                            + "            .email-body_inner {\n"
                            + "                width: 100% !important\n"
                            + "            }\n"
                            + "\n"
                            + "            .email-footer {\n"
                            + "                width: 100% !important\n"
                            + "            }\n"
                            + "        }\n"
                            + "\n"
                            + "        @media only screen and (max-width: 500px) {\n"
                            + "            .button {\n"
                            + "                width: 100% !important\n"
                            + "            }\n"
                            + "        }\n"
                            + "    </style>\n"
                            + "</head>\n"
                            + "\n"
                            + "<body>\n"
                            + "    <div class=\"body\"\n"
                            + "        style=\"-webkit-text-size-adjust: none; box-sizing: border-box; color: #74787e; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; height: 100%; line-height: 1.4; margin: 0; width: 100% !important;\"\n"
                            + "        bgcolor=\"#f2f4f6\">\n"
                            + "\n"
                            + "        <table class=\"email-wrapper\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"\n"
                            + "            style=\"box-sizing: border-box; font-family: Arial, sans-serif; margin: 0; padding: 0; width: 100%;\"\n"
                            + "            bgcolor=\"#f2f4f6\">\n"
                            + "            <tr>\n"
                            + "                <td align=\"center\"\n"
                            + "                    style=\"box-sizing: border-box; font-family: Arial, sans-serif; word-break: break-word;\">\n"
                            + "                    <table class=\"email-content\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"\n"
                            + "                        style=\"box-sizing: border-box; font-family: Arial, sans-serif; margin: 0; padding: 0; width: 100%;\">\n"
                            + "                        <tr>\n"
                            + "                            <td class=\"email-body\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"\n"
                            + "                                style=\"-premailer-cellpadding: 0; -premailer-cellspacing: 0; border-bottom-color: #f2f4f6; border-bottom-style: solid; border-bottom-width: 1px; border-top-color: #f2f4f6; border-top-style: solid; border-top-width: 1px; box-sizing: border-box; font-family: Arial, sans-serif; margin: 0; padding: 0; width: 100%; word-break: break-word;\"\n"
                            + "                                bgcolor=\"#f2f4f6\">\n"
                            + "                                <table class=\"email-body_inner\" align=\"center\" width=\"570\" cellpadding=\"0\"\n"
                            + "                                    cellspacing=\"0\"\n"
                            + "                                    style=\"border-radius: 5px; overflow:hidden;box-sizing: border-box; font-family: Arial, sans-serif; margin: 0 auto; padding: 0; width: 570px;\"\n"
                            + "                                    bgcolor=\"#ffffff\">\n"
                            + "                                    <tr>\n"
                            + "                                        <td><a href=\"#\"><img\n"
                            + "                                                    style=\"height:auto !important;max-width:570px !important;width: 100% !important;\"\n"
                            + "                                                    width=\"570\"\n"
                            + "                                                    src=\"https://www.worldhappiness.com/wp-content/uploads/emails/signup-completed.jpg\"></a>\n"
                            + "                                        </td>\n"
                            + "                                    </tr>\n"
                            + "                                    <tr>\n"
                            + "                                        <td class=\"content-cell\"\n"
                            + "                                            style=\"box-sizing: border-box; font-family: Arial, sans-serif; padding: 35px; word-break: break-word;\">\n"
                            + "                                            <h1 style=\"box-sizing: border-box; color: #2f3133; font-family: Arial, sans-serif; font-size: 19px; font-weight: bold; margin-top: 0;\"\n"
                            + "                                                align=\"left\">Welcome to FuJob</h1>\n"
                            + "                                            <p style=\"box-sizing: border-box; color: #74787e; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                align=\"left\">Thank you for creating an FuJob account.For the next 12\n"
                            + "                                                months, you'll have free access to all FuJob services within the limits.\n"
                            + "                                            </p>\n"
                            + "                                            <p style=\"box-sizing: border-box; color: #74787e; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                align=\"left\">If you are unable to access FuJob Services, please note\n"
                            + "                                                that some services may take up to 24 hours to fully activate. If you're\n"
                            + "                                                still unable to access FuJob Services after that time, please visit <a\n"
                            + "                                                    href=\"#\" style=\"text-decoration: none;\">FuJob Support</a>.\n"
                            + "                                            </p>\n"
                            + "                                            <table class=\"body-action\" align=\"center\" width=\"100%\" cellpadding=\"0\"\n"
                            + "                                                cellspacing=\"0\"\n"
                            + "                                                style=\"box-sizing: border-box; font-family: Arial, sans-serif; margin: 30px auto; padding: 0; text-align: center; width: 100%;\">\n"
                            + "                                                <tr>\n"
                            + "                                                    <td align=\"center\"\n"
                            + "                                                        style=\"box-sizing: border-box; font-family: Arial, sans-serif; word-break: break-word;\">\n"
                            + "                                                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                            + "                                                            style=\"box-sizing: border-box; font-family: Arial, sans-serif;\">\n"
                            + "                                                            <tr>\n"
                            + "                                                                <td align=\"center\"\n"
                            + "                                                                    style=\"box-sizing: border-box; font-family: Arial, sans-serif; word-break: break-word;\">\n"
                            + "                                                                    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                            + "                                                                        style=\"box-sizing: border-box; font-family: Arial, sans-serif;\">\n"
                            + "                                                                        <tr>\n"
                            + "                                                                            <td\n"
                            + "                                                                                style=\"box-sizing: border-box; font-family: Arial, sans-serif; word-break: break-word;\">\n"
                            + "                                                                                <a href=\"http://localhost:8080/FuJob/\"\n"
                            + "                                                                                    class=\"button button--blue\"\n"
                            + "                                                                                    target=\"_blank\"\n"
                            + "                                                                                    style=\"-webkit-text-size-adjust: none; background: #e50555; border-color: #e50555; border-radius: 4px; border-style: solid; border-width: 15px 25px; box-sizing: border-box; color: #ffffff; display: inline-block; font-family: Arial, sans-serif; font-size: 16px; text-decoration: none;font-weight:bold;\">Getting\n"
                            + "                                                                                    Started Resources >></a>\n"
                            + "                                                                            </td>\n"
                            + "                                                                        </tr>\n"
                            + "                                                                    </table>\n"
                            + "                                                                </td>\n"
                            + "                                                            </tr>\n"
                            + "                                                        </table>\n"
                            + "                                                    </td>\n"
                            + "                                                </tr>\n"
                            + "                                            </table>\n"
                            + "                                            <p style=\"box-sizing: border-box; color: #74787e; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                align=\"left\">Welcome to the FuJob community! If you have a moment, share FuJob with friends.</p>\n"
                            + "\n"
                            + "                                            <p style=\"box-sizing: border-box; color: #74787e; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                align=\"left\">Cheers, <br />The FuJob<sup>®</sup> Team</p>\n"
                            + "                                        </td>\n"
                            + "                                    </tr>\n"
                            + "                                </table>\n"
                            + "                            </td>\n"
                            + "                        </tr>\n"
                            + "                        <tr>\n"
                            + "                            <td style=\"box-sizing: border-box; font-family: Arial, sans-serif; word-break: break-word;\">\n"
                            + "                                <table class=\"email-footer\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\"\n"
                            + "                                    style=\"box-sizing: border-box; font-family: Arial, sans-serif; margin: 0 auto; padding: 0; text-align: center; width: 570px;\">\n"
                            + "                                    <tbody>\n"
                            + "                                        <tr>\n"
                            + "                                            <td class=\"content-cell\" align=\"center\"\n"
                            + "                                                style=\"box-sizing: border-box; font-family: Arial, sans-serif; padding: 0px 35px; word-break: break-word;\">\n"
                            + "                                                <table width=\"100%\" cellpadding=\"20\" cellspacing=\"0\" border=\"0\">\n"
                            + "                                                    <tbody>\n"
                            + "                                                        <tr>\n"
                            + "                                                            <td align=\"center\">\n"
                            + "                                                                <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                            + "                                                                    <tbody>\n"
                            + "                                                                        <tr>\n"
                            + "                                                                            <td class=\"img\"\n"
                            + "                                                                                style=\"font-size:0pt; line-height:0pt; text-align:left\"\n"
                            + "                                                                                width=\"50\"><a\n"
                            + "                                                                                    href=\"https://www.facebook.com\"\n"
                            + "                                                                                    target=\"_blank\"><img\n"
                            + "                                                                                        src=\"https://www.worldhappiness.com/wp-content/uploads/facebook-circled.png\"\n"
                            + "                                                                                        width=\"50\" height=\"50\"\n"
                            + "                                                                                        alt=\"Facebook\" border=\"0\"></a>\n"
                            + "                                                                            </td>\n"
                            + "                                                                            <td class=\"img\"\n"
                            + "                                                                                style=\"font-size:0pt; line-height:0pt; text-align:left\"\n"
                            + "                                                                                width=\"50\"> <a\n"
                            + "                                                                                    href=\"https://twitter.com\"\n"
                            + "                                                                                    target=\"_blank\"><img\n"
                            + "                                                                                        src=\"https://www.worldhappiness.com/wp-content/uploads/twitter-circled.png\"\n"
                            + "                                                                                        width=\"50\" height=\"50\"\n"
                            + "                                                                                        alt=\"Twitter\" border=\"0\"></a>\n"
                            + "                                                                            </td>\n"
                            + "                                                                            <td class=\"img\"\n"
                            + "                                                                                style=\"font-size:0pt; line-height:0pt; text-align:left; padding:4px\"\n"
                            + "                                                                                width=\"44\"> <a\n"
                            + "                                                                                    href=\"https://www.youtube.com\"\n"
                            + "                                                                                    target=\"_blank\"><img\n"
                            + "                                                                                        src=\"https://img.icons8.com/flat_round/64/000000/youtube-play.png\"\n"
                            + "                                                                                        width=\"43\" height=\"43\"\n"
                            + "                                                                                        alt=\"Youtube\" border=\"0\"></a>\n"
                            + "                                                                            </td>\n"
                            + "                                                                            <td class=\"img\"\n"
                            + "                                                                                style=\"font-size:0pt; line-height:0pt; text-align:left\"\n"
                            + "                                                                                width=\"41\"> <a\n"
                            + "                                                                                    href=\"https://www.instagram.com\"\n"
                            + "                                                                                    target=\"_blank\"><img\n"
                            + "                                                                                        src=\"https://www.worldhappiness.com/wp-content/uploads/linkedin-circled.png\"\n"
                            + "                                                                                        width=\"50\" height=\"50\"\n"
                            + "                                                                                        alt=\"Instagram\" border=\"0\"></a>\n"
                            + "                                                                            </td>\n"
                            + "                                                                        </tr>\n"
                            + "                                                                    </tbody>\n"
                            + "                                                                </table>\n"
                            + "                                                            </td>\n"
                            + "                                                        </tr>\n"
                            + "                                                    </tbody>\n"
                            + "                                                </table>\n"
                            + "                                                <p class=\"sub align-center\"\n"
                            + "                                                    style=\"box-sizing: border-box; color: #bbbfc3; font-family: Arial, sans-serif; font-size: 12px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                    align=\"center\">© 2022 FuJob. All rights reserved.</p>\n"
                            + "                                                <p class=\"sub align-center\"\n"
                            + "                                                    style=\"box-sizing: border-box; color: #bbbfc3; font-family: Arial, sans-serif; font-size: 12px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                    align=\"center\">District 9, HCM City.\n"
                            + "                                                </p>\n"
                            + "                                            </td>\n"
                            + "                                        </tr>\n"
                            + "                                    </tbody>\n"
                            + "                                </table>\n"
                            + "                            </td>\n"
                            + "                        </tr>\n"
                            + "                    </table>\n"
                            + "                </td>\n"
                            + "            </tr>\n"
                            + "        </table>\n"
                            + "    </div>\n"
                            + "</body>\n"
                            + "\n"
                            + "</html>";
                    break;
                case "forgot":
                    JwtTokenUtils jwtTokenUtils = new JwtTokenUtils();
                    String token = jwtTokenUtils.generateToken(repliient);
                    subject = EMAIL_FORGOT_PASSWORD;
                    content = "<!DOCTYPE html>\n"
                            + "<html lang=\"en\" class=\"no-js\">\n"
                            + "\n"
                            + "<head>\n"
                            + "    <meta charset=\"UTF-8\">\n"
                            + "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\n"
                            + "    <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />\n"
                            + "    <style type=\"text/css\">\n"
                            + "        .body {\n"
                            + "            width: 100% !important;\n"
                            + "            height: 100%;\n"
                            + "            margin: 0;\n"
                            + "            line-height: 1.4;\n"
                            + "            background-color: #f2f4f6;\n"
                            + "            color: #74787e;\n"
                            + "            -webkit-text-size-adjust: none\n"
                            + "        }\n"
                            + "\n"
                            + "        @media only screen and (max-width: 600px) {\n"
                            + "            .email-body_inner {\n"
                            + "                width: 100% !important\n"
                            + "            }\n"
                            + "\n"
                            + "            .email-footer {\n"
                            + "                width: 100% !important\n"
                            + "            }\n"
                            + "        }\n"
                            + "\n"
                            + "        @media only screen and (max-width: 500px) {\n"
                            + "            .button {\n"
                            + "                width: 100% !important\n"
                            + "            }\n"
                            + "        }\n"
                            + "    </style>\n"
                            + "</head>\n"
                            + "\n"
                            + "<body>\n"
                            + "    <div class=\"body\"\n"
                            + "        style=\"-webkit-text-size-adjust: none; box-sizing: border-box; color: #74787e; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; height: 100%; line-height: 1.4; margin: 0; width: 100% !important;\"\n"
                            + "        bgcolor=\"#f2f4f6\">\n"
                            + "\n"
                            + "        <table class=\"email-wrapper\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"\n"
                            + "            style=\"box-sizing: border-box; font-family: Arial, sans-serif; margin: 0; padding: 0; width: 100%;\"\n"
                            + "            bgcolor=\"#f2f4f6\">\n"
                            + "            <tr>\n"
                            + "                <td align=\"center\"\n"
                            + "                    style=\"box-sizing: border-box; font-family: Arial, sans-serif; word-break: break-word;\">\n"
                            + "                    <table class=\"email-content\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"\n"
                            + "                        style=\"box-sizing: border-box; font-family: Arial, sans-serif; margin: 0; padding: 0; width: 100%;\">\n"
                            + "                        <tr>\n"
                            + "                            <td class=\"email-body\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"\n"
                            + "                                style=\"-premailer-cellpadding: 0; -premailer-cellspacing: 0; border-bottom-color: #f2f4f6; border-bottom-style: solid; border-bottom-width: 1px; border-top-color: #f2f4f6; border-top-style: solid; border-top-width: 1px; box-sizing: border-box; font-family: Arial, sans-serif; margin: 0; padding: 0; width: 100%; word-break: break-word;\"\n"
                            + "                                bgcolor=\"#f2f4f6\">\n"
                            + "                                <table class=\"email-body_inner\" align=\"center\" width=\"570\" cellpadding=\"0\"\n"
                            + "                                    cellspacing=\"0\"\n"
                            + "                                    style=\"border-radius: 5px; overflow:hidden;box-sizing: border-box; font-family: Arial, sans-serif; margin: 0 auto; padding: 0; width: 570px;\"\n"
                            + "                                    bgcolor=\"#ffffff\">\n"
                            + "                                    <tr>\n"
                            + "                                        <td><a href=\"#\"><img\n"
                            + "                                                    style=\"height:auto !important;max-width:570px !important;width: 100% !important;\"\n"
                            + "                                                    width=\"570\"\n"
                            + "                                                    src=\"https://img.lovepik.com/background/20211021/large/lovepik-financial-bank-password-security-background-image_500511021.jpg\"></a>\n"
                            + "                                        </td>\n"
                            + "                                    </tr>\n"
                            + "                                    <tr>\n"
                            + "                                        <td class=\"content-cell\"\n"
                            + "                                            style=\"box-sizing: border-box; font-family: Arial, sans-serif; padding: 35px; word-break: break-word;\">\n"
                            + "                                            <h1 style=\"box-sizing: border-box; color: #2f3133; font-family: Arial, sans-serif; font-size: 19px; font-weight: bold; margin-top: 0;\"\n"
                            + "                                                align=\"left\">FuJob password reset</h1>\n"
                            + "                                            <p style=\"box-sizing: border-box; color: #74787e; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                align=\"left\">We heard that you lost your FuJob password. Sorry about\n"
                            + "                                                that!\n"
                            + "                                            </p>\n"
                            + "                                            <p style=\"box-sizing: border-box; color: #74787e; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                align=\"left\">But do not worry! You can use the following button to reset\n"
                            + "                                                your password:\n"
                            + "                                            </p>\n"
                            + "                                            <table class=\"body-action\" align=\"center\" width=\"100%\" cellpadding=\"0\"\n"
                            + "                                                cellspacing=\"0\"\n"
                            + "                                                style=\"box-sizing: border-box; font-family: Arial, sans-serif; margin: 30px auto; padding: 0; text-align: center; width: 100%;\">\n"
                            + "                                                <tr>\n"
                            + "                                                    <td align=\"center\"\n"
                            + "                                                        style=\"box-sizing: border-box; font-family: Arial, sans-serif; word-break: break-word;\">\n"
                            + "                                                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                            + "                                                            style=\"box-sizing: border-box; font-family: Arial, sans-serif;\">\n"
                            + "                                                            <tr>\n"
                            + "                                                                <td align=\"center\"\n"
                            + "                                                                    style=\"box-sizing: border-box; font-family: Arial, sans-serif; word-break: break-word;\">\n"
                            + "                                                                    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                            + "                                                                        style=\"box-sizing: border-box; font-family: Arial, sans-serif;\">\n"
                            + "                                                                        <tr>\n"
                            + "                                                                            <td\n"
                            + "                                                                                style=\"box-sizing: border-box; font-family: Arial, sans-serif; word-break: break-word;\">\n"
                            + "                                                                                <a href=\"http://localhost:8080/FuJob/RecoveryPasswordHandler?token="+token+"\"\n"
                            + "                                                                                    class=\"button button--blue\"\n"
                            + "                                                                                    target=\"_blank\"\n"
                            + "                                                                                    style=\"-webkit-text-size-adjust: none; background: #17093b; border-color: #17093b; border-radius: 4px; border-style: solid; border-width: 15px 25px; box-sizing: border-box; color: #ffffff; display: inline-block; font-family: Arial, sans-serif; font-size: 16px; text-decoration: none;font-weight:bold;\">Reset\n"
                            + "                                                                                    your password</a>\n"
                            + "                                                                            </td>\n"
                            + "                                                                        </tr>\n"
                            + "                                                                    </table>\n"
                            + "                                                                </td>\n"
                            + "                                                            </tr>\n"
                            + "                                                        </table>\n"
                            + "                                                    </td>\n"
                            + "                                                </tr>\n"
                            + "                                            </table>\n"
                            + "                                            <p style=\"box-sizing: border-box; color: #74787e; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                align=\"left\">If you don’t use this link within 15 mins, it will expire.\n"
                            + "                                                To get a new password reset link, visit: <a\n"
                            + "                                                    href=\"http://localhost:8080/FuJob/view/recovery_password.jsp\">http://localhost:8080/FuJob/view/recovery_password.jsp</a>\n"
                            + "                                            </p>\n"
                            + "\n"
                            + "                                            <p style=\"box-sizing: border-box; color: #74787e; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                align=\"left\">Thanks, <br />The FuJob<sup>®</sup> Team</p>\n"
                            + "                                        </td>\n"
                            + "                                    </tr>\n"
                            + "                                </table>\n"
                            + "                            </td>\n"
                            + "                        </tr>\n"
                            + "                        <tr>\n"
                            + "                            <td style=\"box-sizing: border-box; font-family: Arial, sans-serif; word-break: break-word;\">\n"
                            + "                                <table class=\"email-footer\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\"\n"
                            + "                                    style=\"box-sizing: border-box; font-family: Arial, sans-serif; margin: 0 auto; padding: 0; text-align: center; width: 570px;\">\n"
                            + "                                    <tbody>\n"
                            + "                                        <tr>\n"
                            + "                                            <td class=\"content-cell\" align=\"center\"\n"
                            + "                                                style=\"box-sizing: border-box; font-family: Arial, sans-serif; padding: 0px 35px; word-break: break-word;\">\n"
                            + "                                                <table width=\"100%\" cellpadding=\"20\" cellspacing=\"0\" border=\"0\">\n"
                            + "                                                    <tbody>\n"
                            + "                                                        <tr>\n"
                            + "                                                            <td align=\"center\">\n"
                            + "                                                                <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n"
                            + "                                                                    <tbody>\n"
                            + "                                                                        <tr>\n"
                            + "                                                                            <td class=\"img\"\n"
                            + "                                                                                style=\"font-size:0pt; line-height:0pt; text-align:left\"\n"
                            + "                                                                                width=\"50\"><a\n"
                            + "                                                                                    href=\"https://www.facebook.com\"\n"
                            + "                                                                                    target=\"_blank\"><img\n"
                            + "                                                                                        src=\"https://www.worldhappiness.com/wp-content/uploads/facebook-circled.png\"\n"
                            + "                                                                                        width=\"50\" height=\"50\"\n"
                            + "                                                                                        alt=\"Facebook\" border=\"0\"></a>\n"
                            + "                                                                            </td>\n"
                            + "                                                                            <td class=\"img\"\n"
                            + "                                                                                style=\"font-size:0pt; line-height:0pt; text-align:left\"\n"
                            + "                                                                                width=\"50\"> <a\n"
                            + "                                                                                    href=\"https://twitter.com\"\n"
                            + "                                                                                    target=\"_blank\"><img\n"
                            + "                                                                                        src=\"https://www.worldhappiness.com/wp-content/uploads/twitter-circled.png\"\n"
                            + "                                                                                        width=\"50\" height=\"50\"\n"
                            + "                                                                                        alt=\"Twitter\" border=\"0\"></a>\n"
                            + "                                                                            </td>\n"
                            + "                                                                            <td class=\"img\"\n"
                            + "                                                                                style=\"font-size:0pt; line-height:0pt; text-align:left; padding:4px\"\n"
                            + "                                                                                width=\"44\"> <a\n"
                            + "                                                                                    href=\"https://www.youtube.com\"\n"
                            + "                                                                                    target=\"_blank\"><img\n"
                            + "                                                                                        src=\"https://img.icons8.com/flat_round/64/000000/youtube-play.png\"\n"
                            + "                                                                                        width=\"43\" height=\"43\"\n"
                            + "                                                                                        alt=\"Youtube\" border=\"0\"></a>\n"
                            + "                                                                            </td>\n"
                            + "                                                                            <td class=\"img\"\n"
                            + "                                                                                style=\"font-size:0pt; line-height:0pt; text-align:left\"\n"
                            + "                                                                                width=\"41\"> <a\n"
                            + "                                                                                    href=\"https://www.instagram.com\"\n"
                            + "                                                                                    target=\"_blank\"><img\n"
                            + "                                                                                        src=\"https://www.worldhappiness.com/wp-content/uploads/linkedin-circled.png\"\n"
                            + "                                                                                        width=\"50\" height=\"50\"\n"
                            + "                                                                                        alt=\"Instagram\" border=\"0\"></a>\n"
                            + "                                                                            </td>\n"
                            + "                                                                        </tr>\n"
                            + "                                                                    </tbody>\n"
                            + "                                                                </table>\n"
                            + "                                                            </td>\n"
                            + "                                                        </tr>\n"
                            + "                                                    </tbody>\n"
                            + "                                                </table>\n"
                            + "                                                <p class=\"sub align-center\"\n"
                            + "                                                    style=\"box-sizing: border-box; color: #bbbfc3; font-family: Arial, sans-serif; font-size: 12px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                    align=\"center\">© 2022 FuJob. All rights reserved.</p>\n"
                            + "                                                <p class=\"sub align-center\"\n"
                            + "                                                    style=\"box-sizing: border-box; color: #bbbfc3; font-family: Arial, sans-serif; font-size: 12px; line-height: 1.5em; margin-top: 0;\"\n"
                            + "                                                    align=\"center\">District 9, HCM City.\n"
                            + "                                                </p>\n"
                            + "                                            </td>\n"
                            + "                                        </tr>\n"
                            + "                                    </tbody>\n"
                            + "                                </table>\n"
                            + "                            </td>\n"
                            + "                        </tr>\n"
                            + "                    </table>\n"
                            + "                </td>\n"
                            + "            </tr>\n"
                            + "        </table>\n"
                            + "    </div>\n"
                            + "</body>\n"
                            + "\n"
                            + "</html>";
                    break;
                default:
                    subject = "FuJob";
                    content = "Maybe this email is wrong, don't care about it!";
            }
            EmailUtils.sendEmail(host, port, user, pass, repliient.getEmail(), subject, content);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
